"""Tests for report generation."""
import json
import os
import tempfile

from toxindb.heuristics import Alert
from toxindb.provenance import ProvenanceReport
from toxindb.report import render_markdown_report, render_json_report, write_report


def _make_alerts():
    return [
        Alert("TX-001", "Demand Concentration", "high", "q1",
              ["d1", "d2"], "80% recent docs", 0.8),
        Alert("TX-004", "Canary Resurgence", "critical", "q2",
              ["canary-doc"], "Canary surfaced", 1.0),
        Alert("TX-007", "Query-Doc Mismatch", "medium", "q3",
              ["d5"], "High lexical distance", 0.6),
    ]


def _make_provenance():
    return ProvenanceReport(
        total_docs=100, signed_docs=95, unsigned_docs=5,
        unique_sources=5, unique_owners=4,
        source_owner_map={"wiki": "wiki-owner"},
        issues=[{"type": "unsigned_among_signed", "doc_id": "d5",
                 "source": "wiki", "severity": "medium",
                 "detail": "Doc d5 unsigned"}],
    )


def test_render_markdown_report():
    alerts = _make_alerts()
    md = render_markdown_report(alerts)
    assert "# toxindb" in md
    assert "TX-001" in md
    assert "TX-004" in md
    assert "Critical" in md
    assert "Generated by toxindb" in md


def test_render_markdown_with_provenance():
    alerts = _make_alerts()
    prov = _make_provenance()
    md = render_markdown_report(alerts, provenance=prov)
    assert "Provenance Audit" in md
    assert "Signed: 95" in md
    assert "unsigned_among_signed" in md


def test_render_markdown_with_canaries():
    alerts = _make_alerts()
    canary_results = [
        {"canary_id": "c1", "resurfaced": True, "query_id": "q1"},
        {"canary_id": "c2", "resurfaced": False},
    ]
    md = render_markdown_report(alerts, canary_results=canary_results)
    assert "Canary Status" in md
    assert "RESURFACED" in md
    assert "SAFE" in md


def test_render_json_report():
    alerts = _make_alerts()
    jr = render_json_report(alerts)
    data = json.loads(jr)
    assert "alerts" in data
    assert len(data["alerts"]) == 3
    assert "generated_at" in data


def test_render_json_with_provenance():
    alerts = _make_alerts()
    prov = _make_provenance()
    jr = render_json_report(alerts, provenance=prov)
    data = json.loads(jr)
    assert "provenance" in data
    assert data["provenance"]["total_docs"] == 100


def test_write_report():
    with tempfile.TemporaryDirectory() as tmpdir:
        path = write_report("test content", tmpdir, "test.md")
        assert os.path.exists(path)
        with open(path) as f:
            assert f.read() == "test content"


def test_write_report_creates_dir():
    with tempfile.TemporaryDirectory() as tmpdir:
        subdir = os.path.join(tmpdir, "sub", "dir")
        path = write_report("content", subdir, "out.md")
        assert os.path.exists(path)


def test_render_markdown_empty_alerts():
    md = render_markdown_report([])
    assert "**Total alerts:** 0" in md
    assert "Generated by toxindb" in md


def test_render_json_empty_alerts():
    jr = render_json_report([])
    data = json.loads(jr)
    assert data["alert_count"] == 0


def test_render_markdown_long_doc_list():
    alerts = [Alert("TX-001", "test", "high", "q1",
                     [f"d-{i}" for i in range(20)], "detail")]
    md = render_markdown_report(alerts)
    assert "15 more" in md


def test_render_markdown_severity_counts():
    alerts = [
        Alert("TX-001", "a", "critical", None, [], "d"),
        Alert("TX-001", "a", "critical", None, [], "d"),
        Alert("TX-002", "b", "high", None, [], "d"),
    ]
    md = render_markdown_report(alerts)
    assert "**Critical:** 2" in md
    assert "**High:** 1" in md
