"""Report generation — renders Markdown and JSON."""
from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from typing import List, Dict, Any, Optional

from .heuristics import Alert
from .provenance import ProvenanceReport


def render_markdown_report(alerts: List[Alert],
                           provenance: Optional[ProvenanceReport] = None,
                           canary_results: Optional[List[dict]] = None,
                           title: str = "toxindb Analysis Report",
                           trace_path: str = "") -> str:
    lines = []
    lines.append(f"# {title}")
    lines.append("")
    lines.append(f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}")
    if trace_path:
        lines.append(f"**Trace:** `{trace_path}`")
    lines.append("")

    severity_counts: Dict[str, int] = {}
    for alert in alerts:
        severity_counts[alert.severity] = severity_counts.get(alert.severity, 0) + 1

    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Total alerts:** {len(alerts)}")
    for sev in ("critical", "high", "medium", "low"):
        count = severity_counts.get(sev, 0)
        if count > 0:
            lines.append(f"- **{sev.title()}:** {count}")
    lines.append("")

    heuristic_counts: Dict[str, int] = {}
    for alert in alerts:
        heuristic_counts[alert.heuristic_id] = heuristic_counts.get(alert.heuristic_id, 0) + 1
    if heuristic_counts:
        lines.append("### Alerts by Heuristic")
        lines.append("")
        for hid, count in sorted(heuristic_counts.items()):
            lines.append(f"| {hid} | {count} |")
        lines.append("")

    if provenance:
        lines.append("## Provenance Audit")
        lines.append("")
        lines.append(f"- Total documents: {provenance.total_docs}")
        lines.append(f"- Signed: {provenance.signed_docs}")
        lines.append(f"- Unsigned: {provenance.unsigned_docs}")
        lines.append(f"- Unique sources: {provenance.unique_sources}")
        lines.append(f"- Unique owners: {provenance.unique_owners}")
        if provenance.issues:
            lines.append("")
            lines.append("### Provenance Issues")
            lines.append("")
            for issue in provenance.issues:
                lines.append(f"- **{issue['type']}** ({issue['severity']}): {issue['detail']}")
        lines.append("")

    if canary_results:
        lines.append("## Canary Status")
        lines.append("")
        for cr in canary_results:
            status = "RESURFACED" if cr.get("resurfaced") else "SAFE"
            lines.append(f"- Canary `{cr['canary_id']}`: **{status}**")
        lines.append("")

    if alerts:
        lines.append("## Detailed Alerts")
        lines.append("")
        for alert in alerts:
            lines.append(f"### {alert.heuristic_id}: {alert.heuristic_name}")
            lines.append("")
            lines.append(f"- **Severity:** {alert.severity}")
            lines.append(f"- **Confidence:** {alert.confidence:.2f}")
            if alert.query_id:
                lines.append(f"- **Query ID:** `{alert.query_id}`")
            if alert.doc_ids:
                lines.append(f"- **Documents:** {', '.join(f'`{d}`' for d in alert.doc_ids[:5])}")
                if len(alert.doc_ids) > 5:
                    lines.append(f"  - ... and {len(alert.doc_ids) - 5} more")
            lines.append(f"- **Detail:** {alert.detail}")
            lines.append("")

    lines.append("---")
    lines.append("*Generated by toxindb — RAG retrieval-time poisoning detector*")
    lines.append("")
    return "\n".join(lines)


def render_json_report(alerts: List[Alert],
                       provenance: Optional[ProvenanceReport] = None,
                       canary_results: Optional[List[dict]] = None) -> str:
    report = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "alert_count": len(alerts),
        "alerts": [a.to_dict() for a in alerts],
    }
    if provenance:
        report["provenance"] = provenance.to_dict()
    if canary_results:
        report["canary_results"] = canary_results
    return json.dumps(report, indent=2)


def write_report(content: str, output_dir: str, filename: str) -> str:
    os.makedirs(output_dir, exist_ok=True)
    path = os.path.join(output_dir, filename)
    with open(path, "w") as f:
        f.write(content)
    return path
